"""attempt integrity fields

Revision ID: d1ef8760b907
Revises: b9161e9ccd74
Create Date: 2025-08-30 11:14:07.402345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ef8760b907'
down_revision: Union[str, None] = 'b9161e9ccd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quiz_attempts_created_at'), 'quiz_attempts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_created_at'), table_name='quiz_attempts')
    # ### end Alembic commands ###
